[libraries]
Src.files = [
    "src/alu.vhdl",
    "src/constants.vhdl",
    "src/register_bank.vhdl",
    "src/state_register/multiplexor_2to1.vhdl",
    "src/state_register/register_lib.vhdl",
    "src/state_register/state_register.vhdl",
]
Tests.files = [
    "tests/clock.vhdl",
    "tests/alu_tb.vhdl",
    "tests/register_bank_tb.vhdl",
    "tests/multiplexor_2to1_tb.vhdl",
    "tests/register_tb.vhdl",
    "tests/state_register_tb.vhdl",
]
