[libraries]
Src.files = [
    "src/alu.vhdl",
    "src/constants.vhdl",
    "src/register_bank.vhdl",
]
Tests.files = [
    "tests/clock.vhdl",
    "tests/alu_tb.vhdl",
    "tests/register_bank_tb.vhdl",
]
